-- Seed: real Da Nang coworking spaces + activities.
-- Prerequisites: run supabase/11-coworking-activities.sql first (tables + RLS).
-- Safe to re-run (upsert on id). Prices are approximate USD; see price_note.
-- FX assumption ~25,000 VND = $1 (round numbers).

-- ========== COWORKING SPACES ==========
insert into public.coworking_spaces (
  id, name, area_id, neighbourhood_label, description, address,
  day_pass_usd, monthly_usd, price_note, wifi_note, best_for,
  website_url, maps_url, tags, sort_order, published
) values
(
  'cw-ace',
  'ACE Coworking',
  'DN-A',
  'My An / An Thuong edge',
  'Three-floor coworking + café just outside the An Thuong grid. Ergonomic desks, phone booths, meeting room, and a strong community calendar (pickleball, beach hangouts, refresh & connect). Café downstairs delivers to your desk.',
  '12 Trần Văn Dư, Bắc Mỹ An, Ngũ Hành Sơn, Đà Nẵng',
  8, 140,
  'Approx. from published VND: day ~200k (~$8), monthly ~3.5m (~$140). Confirm current rates.',
  'Business-grade wifi; ethernet available on fixed-desk upgrade',
  'Nomads who want community events + reliable Zoom setup near An Thuong',
  'https://acecoworking.vn/',
  'https://www.google.com/maps/search/?api=1&query=ACE+Coworking+12+Tran+Van+Du+Da+Nang',
  array['community', 'café', 'events', 'phone booths'],
  1, true
),
(
  'cw-coworking-danang',
  'Coworking Danang',
  'DN-A',
  'Khuê Mỹ (near My An)',
  'Garden-centred cowork with focus rooms, outdoor terrace, call booths, and a lively member community (weekly lunches, sports, ice bath). Quieter pocket near the beach resorts rather than the An Thuong bar strip.',
  '28 Trần Văn Thành, Khuê Mỹ, Ngũ Hành Sơn, Đà Nẵng',
  10, 140,
  'Approx: 3h 150k, day 250k (~$10), weekly 1.2m, monthly 3.5m (~$140). Fixed desk +1m/mo.',
  'Business-grade fibre; weekly/monthly members can get 24/7 access',
  'People who want community + garden breaks between deep-work blocks',
  'https://coworkingdanang.com/',
  'https://www.google.com/maps/search/?api=1&query=Coworking+Danang+28+Tran+Van+Thanh',
  array['garden', 'community', '24/7 option', 'focus rooms'],
  2, true
),
(
  'cw-hana',
  'Hana''s Coworking',
  'DN-A',
  'Khuê Mỹ / My An',
  'Locally run, budget-friendly cowork with garden courtyard, free monitors, phone booths, and an especially helpful host community for new arrivals. Long daily hours; popular with short-stay nomads.',
  '69 Bùi Tá Hán, Khuê Mỹ, Ngũ Hành Sơn, Đà Nẵng',
  5, 80,
  'Approx: 3h 70k, day 130k (~$5), weekly 550k, monthly 2m (~$80); fixed desk +500k.',
  'Strong wifi reported by members; monitors free on-site',
  'Budget-conscious freelancers who want a welcoming local host',
  'https://hanacoworkingdanang.com/',
  'https://www.google.com/maps/search/?api=1&query=Hana+Coworking+69+Bui+Ta+Han+Da+Nang',
  array['budget', 'community', 'garden', 'monitors'],
  3, true
),
(
  'cw-hive',
  'HIVE Danang',
  'DN-A',
  'An Thuong / Mỹ An',
  'Café downstairs, dedicated focus and studio floors upstairs, plus rooftop. Sit-stand desks and external monitors on the focus floor. Wellness-leaning vibe (sauna/cold plunge mentioned by the venue) in the heart of the expat grid.',
  '48 An Thượng 5, Bắc Mỹ An, Ngũ Hành Sơn, Đà Nẵng',
  6, 90,
  'Day/monthly rates vary — ask on site or via their Carrd/Facebook. Expect mid-range An Thuong pricing.',
  'Desk monitors and booths available on work floors',
  'An Thuong residents who want café energy + a proper desk upstairs',
  'https://hivedanang.carrd.co',
  'https://www.google.com/maps/search/?api=1&query=HIVE+48+An+Thuong+5+Da+Nang',
  array['café', 'rooftop', 'sit-stand', 'wellness'],
  4, true
),
(
  'cw-hub',
  'The Hub Danang',
  'DN-A',
  'Ngũ Hành Sơn (Che Lan Vien)',
  'English-friendly cowork popular with international remote workers near the beach corridor. Day passes and monthly desks; check Facebook for current community events and availability.',
  '27 Chế Lan Viên, Ngũ Hành Sơn, Đà Nẵng',
  7, 90,
  'Pricing not always listed publicly — confirm day vs monthly on Facebook before committing.',
  'Ask about call rooms and wifi speed on your first visit',
  'International nomads wanting a beach-adjacent English-speaking base',
  'https://www.facebook.com/thehubdanang/',
  'https://www.google.com/maps/search/?api=1&query=The+Hub+Danang+27+Che+Lan+Vien',
  array['international', 'beach-adjacent', 'facebook'],
  5, true
),
(
  'cw-seaview',
  'Seaview Coworking Danang',
  'DN-B',
  'An Hải / Son Tra beach-north',
  'Ninth-floor cowork inside Waikiki Beach Hotel — ocean proximity, phone booths, fruit/coffee included. Also offers hotel + desk “stay & work” packages for longer visits.',
  '32 Hà Chương, An Hải, Sơn Trà, Đà Nẵng (Waikiki Beach Hotel, 9th floor)',
  5.5, 80,
  'Approx: 3h 70k, day 135k (~$5.50), weekly 550k, monthly 2m (~$80). Hotel+desk packages separate.',
  'Multiple wifi lines advertised; good for calls with booths',
  'People living north of the river who want beach-side desks',
  'https://seaviewcoworkingdanang.com/',
  'https://www.google.com/maps/search/?api=1&query=Seaview+Coworking+Waikiki+Beach+Hotel+Da+Nang',
  array['seaview', 'hotel', 'beach-north', 'stay-work'],
  6, true
),
(
  'cw-enosta',
  'Enosta Space',
  'DN-B',
  'Sơn Trà (An Nhon 3)',
  'One of Da Nang’s longer-running cowork brands (formerly Enouvo Space). Hot desks, fixed desks, private offices, meeting rooms, and a café — geared to freelancers, startups, and longer stays. Extra event/café locations nearby.',
  '16–18 An Nhơn 3, Sơn Trà, Đà Nẵng',
  4.5, 92,
  'Approx from site: hot desk from ~110k/day (~$4.50), fixed desk from ~2.3m/mo (~$92). Private offices higher.',
  'High-speed internet + meeting rooms; weekday-focused hours',
  'Professionals and teams wanting offices/meeting rooms in Son Tra',
  'https://enostaspace.com/',
  'https://www.google.com/maps/search/?api=1&query=Enosta+Space+16+An+Nhon+3+Da+Nang',
  array['established', 'offices', 'startup', 'son-tra'],
  7, true
),
(
  'cw-dnc',
  'DNC – Danang Coworking Space',
  'DN-C',
  'Hải Châu / Trần Phú',
  'City-centre cowork linked to DNES (Da Nang Business Incubator). Larger footprint with a more startup / SME community mix than the beach nomad hubs — useful if you live central or need a professional downtown address.',
  '31 Trần Phú, Hải Châu, Đà Nẵng',
  8, 100,
  'Confirm current day/monthly rates with DNC/DNES — city pricing often competitive vs beach strips.',
  'Modern infrastructure aimed at startups and local businesses',
  'Founders and professionals based in Hai Chau / CBD',
  'https://coworking.dnes.vn/en/home-page/',
  'https://www.google.com/maps/search/?api=1&query=Danang+Coworking+Space+31+Tran+Phu',
  array['city', 'startup', 'incubator', 'cbd'],
  8, true
),
(
  'cw-an-thuong-cafes',
  'An Thuong café-cowork circuit',
  'DN-A',
  'My An / An Thuong',
  'Not one venue — the densest strip of laptop-friendly cafés (specialty coffee, bakeries, and hybrid work cafés). Great for variety and social days; wifi quality varies by shop, so keep a data SIM for important calls.',
  'An Thượng streets, Bắc Mỹ An, Ngũ Hành Sơn, Đà Nẵng',
  3, null,
  'Drink spend typically ~$2–5 per session; some cafés have soft day minimums.',
  'Café wifi is mixed — fibre coworks nearby are more reliable for Zoom',
  'Remote workers who want walkable variety and café atmosphere',
  null,
  'https://www.google.com/maps/search/?api=1&query=An+Thuong+Da+Nang',
  array['cafés', 'flexible', 'social', 'walkable'],
  9, true
),
(
  'cw-tiktak-thai-phien',
  'Tiktak Coworking (Thái Phiên)',
  'DN-C',
  'Hải Châu (Thái Phiên)',
  'Vietnamese cowork chain location in the city — a practical alternative to beach-strip spaces when you want a more local/urban work day closer to the river and CBD amenities.',
  'Thái Phiên, Hải Châu, Đà Nẵng',
  6, 80,
  'Chain pricing changes by branch — check tiktak.com.vn for the Thái Phiên Da Nang rates.',
  'Standard cowork wifi; ask about meeting rooms',
  'Residents and visitors working more in Hai Chau than My An',
  'https://tiktak.com.vn/tiktak-4-thai-phien-da-nang/',
  'https://www.google.com/maps/search/?api=1&query=Tiktak+Thai+Phien+Da+Nang',
  array['city', 'chain', 'value'],
  10, true
)
on conflict (id) do update set
  name = excluded.name,
  area_id = excluded.area_id,
  neighbourhood_label = excluded.neighbourhood_label,
  description = excluded.description,
  address = excluded.address,
  day_pass_usd = excluded.day_pass_usd,
  monthly_usd = excluded.monthly_usd,
  price_note = excluded.price_note,
  wifi_note = excluded.wifi_note,
  best_for = excluded.best_for,
  website_url = excluded.website_url,
  maps_url = excluded.maps_url,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- ========== ACTIVITIES ==========
insert into public.activities (
  id, name, category, area_id, neighbourhood_label, description,
  typical_price_usd, price_note, duration_note,
  website_url, maps_url, booking_url, tags, sort_order, published
) values
(
  'act-surf-dnoa',
  'Taster surf lesson — Da Nang Outdoor Adventures',
  'surf',
  'DN-A',
  'My Khe / An Thuong',
  'Beginner-friendly taster on My Khe: beach intro + water time with an instructor, then board rental to practice. Shop is a short walk from the sand in the An Thuong grid.',
  28,
  'Listed ~$28 / 700k VND per adult for the taster package; private lessons higher (~$58).',
  'About 1 hour instruction + 2 hours board practice',
  'https://danangadventures.com/',
  'https://www.google.com/maps/search/?api=1&query=Da+Nang+Outdoor+Adventures+An+Thuong+5',
  'https://danangadventures.com/product/taster-surf-lessons-2026/',
  array['beach', 'beginner-friendly', 'my-khe'],
  1, true
),
(
  'act-surf-coco',
  'Surf lesson or board rental — Coco Surf Danang',
  'surf',
  'DN-A',
  'My Khe Beach',
  'Local surf school and rental shop on/near My Khe with group, semi-private, private, kids, and senior options. Strong reviews for patient instructors and fair rental pricing.',
  35,
  'Lessons and rentals vary by package; board-only rentals often much cheaper than lessons. Confirm on site.',
  'Typically 60–120 minutes for lessons',
  'https://cocosurfdanang.com/',
  'https://www.google.com/maps/search/?api=1&query=Coco+Surf+Danang+Vo+Nguyen+Giap',
  'https://cocosurfdanang.com/',
  array['surf', 'rentals', 'my-khe', 'families'],
  2, true
),
(
  'act-surf-wellness',
  'Surf lesson — Da Nang Wellness',
  'surf',
  'DN-A',
  'Behind My Khe / Ngũ Hành Sơn',
  'Family-run bilingual studio offering tailored surf sessions with instructor Gia. Timing follows swell conditions — book via Facebook/WhatsApp rather than a fixed public calendar.',
  40,
  'About 1m VND (~$40) per session listed; multi-lesson discounts by enquiry.',
  'Session length depends on conditions',
  'https://www.danangwellness.com/',
  'https://www.google.com/maps/search/?api=1&query=Da+Nang+Wellness+93+Le+Huu+Khanh',
  'https://m.me/Danangadventuretour',
  array['surf', 'bilingual', 'small-group'],
  3, true
),
(
  'act-yoga-wellness',
  'Yoga drop-in — Da Nang Wellness',
  'wellness',
  'DN-A',
  'Ngũ Hành Sơn (behind the beach)',
  'English/Vietnamese-friendly yoga for beginners and intermediate levels. Mats provided; occasional beach classes when weather allows. Schedule shifts weekly — message to reserve.',
  10,
  'About 250k VND (~$10) per session; multi-visit packs ~1.1–2m VND.',
  '60–75 minutes typical',
  'https://www.danangwellness.com/',
  'https://www.google.com/maps/search/?api=1&query=Da+Nang+Wellness+93+Le+Huu+Khanh',
  'https://m.me/Danangadventuretour',
  array['yoga', 'drop-in', 'wellness'],
  4, true
),
(
  'act-yoga-amit',
  'Private yoga / Reiki — Yoga with Amit',
  'wellness',
  null,
  'Da Nang & Hội An (by appointment)',
  'Experienced teacher offering private and small-group yoga, Reiki, and EFT by appointment across Da Nang and Hội An. Flexible scheduling for longer-stay expats.',
  40,
  'Private session rates vary by length/location — email to confirm. Not a walk-in studio.',
  'By appointment (usually 60–90 minutes)',
  'https://yogawithamit.com/',
  null,
  'mailto:info@yogawithamit.com',
  array['private', 'yoga', 'reiki', 'appointment'],
  5, true
),
(
  'act-sound-healing',
  'Sound healing — Da Nang Wellness',
  'wellness',
  'DN-A',
  'Ngũ Hành Sơn',
  'Handpan-led sound healing sessions for deep rest between work weeks. Session times vary — check their Facebook or Instagram for the next public slots.',
  12,
  'About 300k VND (~$12) per session listed on their site.',
  'Typically about 1 hour',
  'https://www.danangwellness.com/',
  'https://www.google.com/maps/search/?api=1&query=Da+Nang+Wellness+93+Le+Huu+Khanh',
  'https://m.me/Danangadventuretour',
  array['wellness', 'sound', 'rest'],
  6, true
),
(
  'act-hoi-an-day',
  'Hội An Ancient Town day trip',
  'day-trip',
  null,
  'From Da Nang (~30–45 min south)',
  'Easy coastal escape for lantern streets, tailor shops, and riverside food. Grab, local bus, or private driver all work. Old-town heritage tickets are separate if you enter ticketed houses.',
  15,
  'Transport often $5–25 pp; Hội An heritage ticket ~120k VND if visiting indoor sites. Meals extra.',
  'Full day (or evening lantern visit)',
  null,
  'https://www.google.com/maps/search/?api=1&query=Hoi+An+Ancient+Town',
  null,
  array['weekend', 'culture', 'food', 'unesco'],
  7, true
),
(
  'act-ba-na',
  'Ba Na Hills & Golden Bridge',
  'day-trip',
  null,
  'West of Da Nang (~40–60 min)',
  'Cable-car mountain resort with the Golden Bridge, French Village, Fantasy Park, and cooler air. Crowded on weekends — early tickets help. Buffet and some rides cost extra.',
  38,
  'International adult ticket commonly ~950k–1,000k VND (~$38–40) incl. cable car + most attractions. Resident rates lower. Confirm on Sun World / ticket sites.',
  'Full day recommended',
  'https://www.sunworldbanahills.com/',
  'https://www.google.com/maps/search/?api=1&query=Ba+Na+Hills+Golden+Bridge',
  'https://www.sunworldbanahills.com/',
  array['day-trip', 'cable-car', 'photos', 'family'],
  8, true
),
(
  'act-marble-mountains',
  'Marble Mountains (Ngũ Hành Sơn)',
  'outdoors',
  'DN-E',
  'Hòa Hải / Non Nước',
  'Limestone peaks with caves, pagodas, and coastal viewpoints. Thủy Sơn is the main visit. Optional elevator skips stairs; Am Phu Cave is a separate ticket.',
  2,
  'Thủy Sơn entry ~40k VND (~$1.50–2); elevator ~15k one way; Am Phu Cave ~20k. Cash common.',
  '1.5–2.5 hours',
  null,
  'https://www.google.com/maps/search/?api=1&query=Marble+Mountains+Da+Nang',
  null,
  array['caves', 'views', 'budget', 'half-day'],
  9, true
),
(
  'act-son-tra-loop',
  'Sơn Trà peninsula scooter loop',
  'outdoors',
  'DN-B',
  'Sơn Trà',
  'Classic scooter or Grab loop for viewpoints, quieter forest roads, and monkey-spotting (keep snacks sealed). Best early morning or late afternoon to avoid heat and traffic.',
  5,
  'Mostly fuel / time if you already have a bike; Grab round-trip higher. Free viewpoints.',
  '2–4 hours',
  null,
  'https://www.google.com/maps/search/?api=1&query=Son+Tra+Peninsula+Da+Nang',
  null,
  array['motorbike', 'views', 'free-ish', 'nature'],
  10, true
),
(
  'act-linh-ung',
  'Linh Ứng Pagoda (Lady Buddha)',
  'culture',
  'DN-B',
  'Sơn Trà Peninsula',
  'Home of Da Nang’s tall Lady Buddha statue with sea views. Dress modestly. Often combined with a Sơn Trà loop. Free entry; donations welcome.',
  0,
  'Free entry and parking; donations optional.',
  '30–60 minutes',
  null,
  'https://www.google.com/maps/search/?api=1&query=Linh+Ung+Pagoda+Son+Tra+Da+Nang',
  null,
  array['pagoda', 'free', 'views', 'son-tra'],
  11, true
),
(
  'act-dragon-bridge',
  'Dragon Bridge fire & water show',
  'culture',
  'DN-C',
  'Hải Châu / Han River',
  'Weekend (and holiday) evening show when the dragon bridge breathes fire and water. Free public viewing from the riverbanks and nearby bridges — arrive early for a good spot.',
  0,
  'Free. Typically Sat/Sun evenings around 9pm — confirm local schedule.',
  'Show lasts several minutes; plan 30–60 min including travel',
  null,
  'https://www.google.com/maps/search/?api=1&query=Dragon+Bridge+Da+Nang',
  null,
  array['free', 'evening', 'landmark', 'family'],
  12, true
),
(
  'act-seafood-son-tra',
  'Seafood evening — beach / Sơn Trà corridor',
  'food',
  'DN-B',
  'Sơn Trà / My Khe',
  'Casual seafood dinners from plastic-stool local spots to nicer sit-downs along the beach road. Best as a group — share crab, clams, and grilled fish.',
  20,
  'Roughly $12–40 pp depending on venue and how much you order.',
  'Evening',
  null,
  'https://www.google.com/maps/search/?api=1&query=seafood+My+Khe+Da+Nang',
  null,
  array['food', 'social', 'beach'],
  13, true
),
(
  'act-kayak-snorkel-dnoa',
  'Kayak & snorkel tour — Da Nang Outdoor Adventures',
  'outdoors',
  'DN-A',
  'My Khe coast',
  'Guided coastal kayak with snorkeling time — a good non-surf water day when swell is flat. Book through DNOA’s activity pages.',
  56,
  'Listed around $56 on their site; confirm seasonal availability.',
  'Half-day typical',
  'https://danangadventures.com/',
  'https://www.google.com/maps/search/?api=1&query=Da+Nang+Outdoor+Adventures+An+Thuong+5',
  'https://danangadventures.com/',
  array['kayak', 'snorkel', 'water', 'guided'],
  14, true
),
(
  'act-pickleball-community',
  'Community pickleball (T-Army / ACE circuit)',
  'fitness',
  'DN-A',
  'My An area courts',
  'Recurring open play organised through ACE Coworking and local nomad groups (often Tuesday mornings at T-Army). Bring water and court shoes; RSVP in the community chat when required.',
  5,
  'Court fees vary; sometimes free for community sessions or a small shared fee. Confirm with the weekly RSVP.',
  '1–2 hours',
  'https://acecoworking.vn/',
  'https://www.google.com/maps/search/?api=1&query=T-Army+pickleball+Da+Nang',
  null,
  array['pickleball', 'social', 'fitness', 'community'],
  15, true
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  area_id = excluded.area_id,
  neighbourhood_label = excluded.neighbourhood_label,
  description = excluded.description,
  typical_price_usd = excluded.typical_price_usd,
  price_note = excluded.price_note,
  duration_note = excluded.duration_note,
  website_url = excluded.website_url,
  maps_url = excluded.maps_url,
  booking_url = excluded.booking_url,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

-- Remove placeholder example rows from the original 11- seed (if still present)
delete from public.coworking_spaces
where id in ('cw-an-thuong-hub', 'cw-beach-quiet', 'cw-city-centre');

delete from public.activities
where id in (
  'act-surf-my-khe',
  'act-yoga-dropin',
  'act-seafood-evening',
  'act-motorbike-son-tra'
);
